### ISSUE TITLE
Error in text

### ISSUE THREAD

**Issue by ChristopherBlack22** [learn-co-curriculum/javascript-virtual-dom#10]
### Canvas Link

https://learning.flatironschool.com/courses/1883/pages/reconciliation-in-react?module_item_id=259644

### Concern

"But this rebuilds the entire DOM inside div" should read "But this rebuilds the entire DOM inside ul"

**Comment by AlveeM** [comment]
Hi Christopher, thanks for pointing out the error. 

We have updated the GitHub repo and believe your issue to have been resolved.Note, however, that if you are working in Canvas the changes may not show up there, but they will for future students.

Thanks again for helping us ensure improve our curriculum!
