### ISSUE TITLE
Lesson shows up as lab on Learn

### ISSUE THREAD

**Issue by ivalentine** [learn-co-curriculum/javascript-virtual-dom#3]
This lesson shows up as a lab on Learn, which results in the wrong checkboxes appearing on the right hand side. This means that students are unable to properly complete this lab, and must skip it by clicking the gray "Next lesson" button.

This lesson should be classified as a README.

Affected tracks:
`v-000`

cc @aturkewi

**Comment by aturkewi** [comment]
Looks like it's all set now. Thanks :)
