### ISSUE TITLE
"Virtual Dom" terminology is a bit dated and a bit confusing

### ISSUE THREAD

**Issue by alexgriff** [learn-co-curriculum/javascript-virtual-dom#6]
The React core team has moved away from using the term "Virtual Dom" and in fact no longer uses it in any documentation; students will see the term less and less in the wild and it's known to cause confusion.
https://twitter.com/dan_abramov/status/1066328666341294080
https://medium.com/react-in-depth/inside-fiber-in-depth-overview-of-the-new-reconciliation-algorithm-in-react-e1c04700ef6e

I'd recommend against kicking off a new unit with this terminology. Instead I'd propose a high level overview using terms like [Reconciliation](https://reactjs.org/docs/reconciliation.html) and/or Diffing.
ie "React maintains a big tree / object representing what the DOM "should" look like. It diffs this against what the DOM actually looks like. (The concept of a diff can be explained via GH pull requests) And from there efficiently reconciles the difference and updates the DOM so it's always up to date."

**Comment by maxwellbenton** [comment]
Hey @alexgriff,

Thanks for pointing this out and providing the reference resources. I've added this issue to a [list of tasks](https://github.com/learn-co-curriculum/this-is-react-readme/issues/3) we're going to try and take care of in an upcoming update to the React materials. Seems likely that this lesson will be retired or at least mostly rewritten to avoid confusion. 

I'm leaving this issue open for now; I just wanted to reach out to let you know it's in our work queue. I'll update here when this is resolved.

Thank you!

**Comment by maxwellbenton** [comment]
Hey @alexgriff,

I've rewritten this lesson and replaced the contents regarding Virtual DOM with a brief overview of reconciliation, mainly focused on how React groups DOM updates and runs a diffing algorithm to figure out what to update (and included the links you've given). I went ahead and changes the topic names in the Module 4 track and v8. This should prevent student confusion in the future.

Thank you!
